<?php
function twotimesloginlogout_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;
  $block = array();

  switch ($op) {
    case 'list':
        $block['loginlogout']['info'] = t('Loginlogout');
        break;

    case 'view':
        $blockcontent = '';
		
		if ($user->uid == 0) {
			$blockcontent = l(t('Log-in'), 'user/login', array('rel' => 'nofollow'));
			}
		else {
			$blockcontent = l(t('Log-out'), 'logout', array('rel' => 'nofollow'));
			}
			
	        $block['subject'] = t('Loginlogout');			
	   		$block['content'] = $blockcontent;
	    break;	
  }
	return $block;
}